apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: tenant-pipeline-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tenant-pipeline-component
    app.kubernetes.io/part-of: tenant-pipeline
  name: tenant-pipeline-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: tenant-pipeline-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: tenant-pipeline-component
    spec:
      containers:
      - image: quay.io/hacbs-release-tests/dev-release-team-tenant/tenant-pipeline/tenant-pipeline-component@sha256:8250288cd5a2dc0d8c1d69ef1ac9e893f33fbd285bf27e0b8d99f1169bf2d7ec
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
